CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    displayName VARCHAR(100) NOT NULL
);
CREATE TABLE channels (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    adminId INTEGER REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    channelId INTEGER REFERENCES channels(id) ON DELETE CASCADE,
    authorId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    data TEXT NOT NULL,
    date TIMESTAMP DEFAULT NOW()
);
CREATE TABLE users_to_channel (
    id SERIAL PRIMARY KEY,
    userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
    channelId INTEGER REFERENCES channels(id) ON DELETE CASCADE
);